//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.29 at 11:18:10 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://dotplot.org/dpaas", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package org.dotplot.dpaas.wsdto;
