//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.29 at 11:18:10 PM CEST 
//


package org.dotplot.dpaas.wsdto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WSDotplotjob complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="WSDotplotjob">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="WSFilelist" type="{http://dotplot.org/dpaas}WSFilelist"/>
 *         &lt;element name="WSConfiguration" type="{http://dotplot.org/dpaas}WSConfiguration"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Dotplotjob", propOrder = {

})
public class WSDotplotjob {

    @XmlElement(name = "Filelist", required = true)
    protected WSFilelist filelist;
    @XmlElement(name = "Configuration", required = true)
    protected WSConfiguration configuration;

    /**
     * Gets the value of the filelist property.
     * 
     * @return
     *     possible object is
     *     {@link WSFilelist }
     *     
     */
    public WSFilelist getFilelist() {
        return filelist;
    }

    /**
     * Sets the value of the filelist property.
     * 
     * @param value
     *     allowed object is
     *     {@link WSFilelist }
     *     
     */
    public void setFilelist(WSFilelist value) {
        this.filelist = value;
    }

    /**
     * Gets the value of the configuration property.
     * 
     * @return
     *     possible object is
     *     {@link WSConfiguration }
     *     
     */
    public WSConfiguration getConfiguration() {
        return configuration;
    }

    /**
     * Sets the value of the configuration property.
     * 
     * @param value
     *     allowed object is
     *     {@link WSConfiguration }
     *     
     */
    public void setConfiguration(WSConfiguration value) {
        this.configuration = value;
    }

}
