//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.29 at 11:18:10 PM CEST 
//

package org.dotplot.dpaas.wsdto;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;

/**
 * <p>
 * Java class for WSConfiguration complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="WSConfiguration">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="LUTs" type="{http://dotplot.org/dpaas}luts"/>
 *         &lt;element name="Filter" type="{http://dotplot.org/dpaas}WSFilters"/>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Configuration", propOrder = {

})
public class WSConfiguration {

	@XmlElement(name = "LUTs", required = true)
	protected WSLuts luTs;
	@XmlElement(name = "Filter", required = true)
	protected WSFilters filter;

	/**
	 * Gets the value of the luTs property.
	 * 
	 * @return possible object is {@link WSLuts }
	 * 
	 */
	public WSLuts getLUTs() {
		return luTs;
	}

	/**
	 * Sets the value of the luTs property.
	 * 
	 * @param value
	 *            allowed object is {@link WSLuts }
	 * 
	 */
	public void setLUTs(WSLuts value) {
		this.luTs = value;
	}

	/**
	 * Gets the value of the filter property.
	 * 
	 * @return possible object is {@link WSFilters }
	 * 
	 */
	public WSFilters getFilter() {
		return filter;
	}

	/**
	 * Sets the value of the filter property.
	 * 
	 * @param value
	 *            allowed object is {@link WSFilters }
	 * 
	 */
	public void setFilter(WSFilters value) {
		this.filter = value;
	}

}
