//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2009.06.29 at 11:18:10 PM CEST 
//


package org.dotplot.dpaas.wsdto;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for WSFilterTypes.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="WSFilterTypes">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="org.dotplot.filter.LineFilter"/>
 *     &lt;enumeration value="org.dotplot.filter.KeyWordFilter"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 * 
 */
@XmlType(name = "FilterTypes")
@XmlEnum
public enum WSFilterTypes {

    @XmlEnumValue("org.dotplot.filter.LineFilter")
    ORG_DOTPLOT_FILTER_LINE_FILTER("org.dotplot.filter.LineFilter"),
    @XmlEnumValue("org.dotplot.filter.KeyWordFilter")
    ORG_DOTPLOT_FILTER_KEY_WORD_FILTER("org.dotplot.filter.KeyWordFilter");
    private final String value;

    WSFilterTypes(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static WSFilterTypes fromValue(String v) {
        for (WSFilterTypes c: WSFilterTypes.values()) {
            if (c.value.equals(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
